# fly.toml app configuration file generated for andretesteaguiar on 2023-04-26T16:49:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "andretesteaguiar"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
